apiVersion: apps/v1
kind: Deployment
metadata:
  name: insureme-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insureme
  template:
    metadata:
      labels:
        app: insureme
    spec:
      containers:
      - name: insureme-container
        image: akhilbmenon/staragile-insureme:latest
        ports:
        - containerPort: 8080 

----
apiVersion: v1
kind: Service
metadata:
  name: insureme-service
spec:
  type: NodePort
  selector:
    app: insureme
  ports:
  - port: 80
    targetPort: 8081
    nodePort: 30038
